#index:
#    path: /
#    defaults: { _controller: 'App\Controller\OiseauxController::index' }

home:
    path: /
    defaults: { _controller: 'App\Controller\PortfolioController::home' }

etudes:
    path: /etudes
    defaults: { _controller: 'App\Controller\PortfolioController::etudes' }

creations:
    path: /creations
    defaults: { _controller: 'App\Controller\PortfolioController::creations' }

travaux:
    path: /travaux
    defaults: { _controller: 'App\Controller\PortfolioController::travaux' }

apprendre:
    path: /apprendre
    defaults: { _controller: 'App\Controller\OiseauxController::apprendre' }

apprendreJS:
    path: /apprendreJS
    defaults: { _controller: 'App\Controller\OiseauxController::apprendreJS' }
    methods: POST
    options:
        expose: true

quizzUnOiseau:
    path: /quizzUnOiseau
    defaults: { _controller: 'App\Controller\OiseauxController::quizzUnOiseau' }
#    methods: POST
#    options:
#        expose: true

oiseau:
    path: /oiseau
    defaults: { _controller: 'App\Controller\OiseauxController::oiseau' }



fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"